# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97dc137e2fe312454c557620da24c33fdd3f8d288d2347a6d8b3aa25410ba50bc9cc47085e9a9ffff37a39c5e31b29adf7793f942b7bb9ba5ddea61e48b394a0

test:
  secret_key_base: 78ef6ac8798a210bf123766d41cbba7f759868ff40b6d0b737c86c11bea7cf92f179cd0233244079a547aba58f1045611b454f85ff97cdc2fc74008f155337c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
